# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a8046e3b4de26a9806ef054dd169dcd26cd79460d7f5643f65a47f9f7d1b2f2014df752b496e5e1d72b5bcede796b6e1ccbf0cbf9cbe255db8bf3f9d4801f9b

test:
  secret_key_base: 7adcc3e318e90879fae14c4dc22b290688ed87e8a35210dc5f0ed35cf468e11c36ab36777dfb0bd6495e6ed91a006291da20280f52331efcc6c717167891776d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
